theme: minima
title: Machine Learning
author: Jeevan Bastol
email: jbastol000@citymail.cuny.com
description: > # this means to ignore newlines until "baseurl:"
  Machine learning is one of the most interesting branches of computer science. Machine learning is a reletavely new field and a lot 
  of advaces will be made in future

# social links
instagram_username: https://www.instagram.com/jeevan_bastola_/
github_username:  github.com/Jeevan986

show_excerpts: false # set to false to remove excerpts on the homepage
